AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'tmp/**/*'
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
Style/ClassVars:
  Enabled: false
